version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "npm"
    directory: "/apps/web"
    schedule:
      interval: "daily"
      timezone: "Asia/Seoul"
    open-pull-requests-limit: 1
    allow:
      - dependency-name: "@team-frieeren/*"
    ignore:
      - dependency-name: "@team-frieeren/*"
        update-types: ["version-update:semver-major"]