/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * API Gateway
 * API Gateway for Checkmate application
 * OpenAPI spec version: 1.0
 */
import { http, HttpResponse, delay } from "msw";

export const getAppControllerGetHelloMockHandler = (
  overrideResponse?: void | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<void> | void)
) => {
  return http.get("*/", async info => {
    await delay(1000);
    if (typeof overrideResponse === "function") {
      await overrideResponse(info);
    }
    return new HttpResponse(null, { status: 200 });
  });
};
export const getAppMock = () => [getAppControllerGetHelloMockHandler()];
