/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * time-align API
 * time-align API
 * OpenAPI spec version: 1.0
 */
import { useInfiniteQuery, useQuery, useSuspenseQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";

import { httpClient } from "../../http";

export const appControllerHealthCheck = (signal?: AbortSignal) => {
  return httpClient<void>({ url: "/", method: "GET", signal });
};

export const getAppControllerHealthCheckQueryKey = () => {
  return ["/"] as const;
};

export const getAppControllerHealthCheckInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof appControllerHealthCheck>>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof appControllerHealthCheck>>, TError, TData>>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAppControllerHealthCheckQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof appControllerHealthCheck>>> = ({ signal }) =>
    appControllerHealthCheck(signal);

  return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof appControllerHealthCheck>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AppControllerHealthCheckInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof appControllerHealthCheck>>
>;
export type AppControllerHealthCheckInfiniteQueryError = unknown;

export function useAppControllerHealthCheckInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof appControllerHealthCheck>>>,
  TError = unknown,
>(
  options: {
    query: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof appControllerHealthCheck>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof appControllerHealthCheck>>,
          TError,
          Awaited<ReturnType<typeof appControllerHealthCheck>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAppControllerHealthCheckInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof appControllerHealthCheck>>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof appControllerHealthCheck>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof appControllerHealthCheck>>,
          TError,
          Awaited<ReturnType<typeof appControllerHealthCheck>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAppControllerHealthCheckInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof appControllerHealthCheck>>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof appControllerHealthCheck>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useAppControllerHealthCheckInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof appControllerHealthCheck>>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof appControllerHealthCheck>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAppControllerHealthCheckInfiniteQueryOptions(options);

  const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getAppControllerHealthCheckQueryOptions = <
  TData = Awaited<ReturnType<typeof appControllerHealthCheck>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof appControllerHealthCheck>>, TError, TData>>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAppControllerHealthCheckQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof appControllerHealthCheck>>> = ({ signal }) =>
    appControllerHealthCheck(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof appControllerHealthCheck>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AppControllerHealthCheckQueryResult = NonNullable<Awaited<ReturnType<typeof appControllerHealthCheck>>>;
export type AppControllerHealthCheckQueryError = unknown;

export function useAppControllerHealthCheck<
  TData = Awaited<ReturnType<typeof appControllerHealthCheck>>,
  TError = unknown,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof appControllerHealthCheck>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof appControllerHealthCheck>>,
          TError,
          Awaited<ReturnType<typeof appControllerHealthCheck>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAppControllerHealthCheck<
  TData = Awaited<ReturnType<typeof appControllerHealthCheck>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof appControllerHealthCheck>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof appControllerHealthCheck>>,
          TError,
          Awaited<ReturnType<typeof appControllerHealthCheck>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAppControllerHealthCheck<
  TData = Awaited<ReturnType<typeof appControllerHealthCheck>>,
  TError = unknown,
>(
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof appControllerHealthCheck>>, TError, TData>> },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useAppControllerHealthCheck<
  TData = Awaited<ReturnType<typeof appControllerHealthCheck>>,
  TError = unknown,
>(
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof appControllerHealthCheck>>, TError, TData>> },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAppControllerHealthCheckQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getAppControllerHealthCheckSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof appControllerHealthCheck>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof appControllerHealthCheck>>, TError, TData>>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAppControllerHealthCheckQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof appControllerHealthCheck>>> = ({ signal }) =>
    appControllerHealthCheck(signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof appControllerHealthCheck>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AppControllerHealthCheckSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof appControllerHealthCheck>>
>;
export type AppControllerHealthCheckSuspenseQueryError = unknown;

export function useAppControllerHealthCheckSuspense<
  TData = Awaited<ReturnType<typeof appControllerHealthCheck>>,
  TError = unknown,
>(
  options: {
    query: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof appControllerHealthCheck>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAppControllerHealthCheckSuspense<
  TData = Awaited<ReturnType<typeof appControllerHealthCheck>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof appControllerHealthCheck>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAppControllerHealthCheckSuspense<
  TData = Awaited<ReturnType<typeof appControllerHealthCheck>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof appControllerHealthCheck>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useAppControllerHealthCheckSuspense<
  TData = Awaited<ReturnType<typeof appControllerHealthCheck>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof appControllerHealthCheck>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAppControllerHealthCheckSuspenseQueryOptions(options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
