/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Time-Align API
 * API Gateway
 * OpenAPI spec version: 1.0
 */
import { z as zod } from "zod";

export const authControllerOauthLoginBody = zod.object({
  email: zod.string(),
  name: zod.string(),
  image: zod.string(),
  provider: zod.string(),
  providerId: zod.string(),
});

export const authControllerOauthLoginResponse = zod.object({
  user: zod.object({
    id: zod.number(),
    email: zod.string(),
    name: zod.string(),
  }),
  accessToken: zod.string(),
  refreshToken: zod.string(),
});

export const authControllerRefreshBody = zod.object({
  refreshToken: zod.string(),
});

export const authControllerRefreshResponse = zod.object({
  accessToken: zod.string(),
});
