import { ToastProvider } from "@team-frieeren/components";
import type { Metadata } from "next";
import RQProvider from "../shared/provider/RQProvider";
import SessionProvider from "../shared/provider/SessionProvider";
import "../shared/style/index.css";
import "@team-frieeren/components/styles.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SessionProvider>
          <RQProvider>
            <ToastProvider>{children}</ToastProvider>
          </RQProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
