version: "3"
services:
  nginx:
    container_name: nginx
    image: nginx:stable-otel
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/html:/var/www/html
      - ./nginx/nginx/logs:/var/log/nginx
    depends_on:
      - api-gateway
    environment:
      - TZ=Asia/Seoul

  api:
    build:
      context: ..
      dockerfile: infrastructure/Dockerfile.api
      args:
        APP_NAME: api
    ports:
      - "3003:3003"
    environment:
      - TZ=Asia/Seoul
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - PORT=${API_PORT}
      - MYSQL_HOST=db
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  db:
    image: mysql:latest
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      - TZ=Asia/Seoul
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mysql/data:/var/lib/mysql

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./redis/data:/data
