/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Time-Align API
 * API Gateway
 * OpenAPI spec version: 1.0
 */
import type { CommonResponseDtoData } from "./commonResponseDtoData";

export interface CommonResponseDto {
  statusCode: number;
  message: string;
  data: CommonResponseDtoData;
}
