/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Time-Align API
 * API Gateway
 * OpenAPI spec version: 1.0
 */

export interface CreateScheduleRequestDto {
  title: string;
  description: string;
  startTime: string;
  endTime: string;
  location: string;
  status: string;
  isAllDay: boolean;
  createdAt: string;
  updatedAt: string;
  participants: string[];
}
