/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * time-align API
 * time-align API
 * OpenAPI spec version: 1.0
 */

export interface OAuthLoginUserDto {
  id: number;
  email: string;
  name: string;
}
