/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Time-Align API
 * API Gateway
 * OpenAPI spec version: 1.0
 */

export interface OAuthLoginRequestDto {
  email: string;
  name: string;
  image: string;
  provider: string;
  providerId: string;
}
