/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * time-align API
 * time-align API
 * OpenAPI spec version: 1.0
 */
import type { OAuthLoginUserDto } from "./oAuthLoginUserDto";

export interface OAuthLoginResponseDto {
  user: OAuthLoginUserDto;
  accessToken: string;
  refreshToken: string;
}
