/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Time-Align API
 * API Gateway
 * OpenAPI spec version: 1.0
 */

export interface PageInfo {
  page: number;
  size: number;
  totalElements: number;
  totalPages: number;
}
