/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Time-Align API
 * API Gateway
 * OpenAPI spec version: 1.0
 */
import type { PageInfo } from "./pageInfo";

export interface PaginatedData {
  data: string[];
  pageInfo: PageInfo;
}
