/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Time-Align API
 * API Gateway
 * OpenAPI spec version: 1.0
 */
import type { PaginatedData } from "./paginatedData";

export interface QueryScheduleResponseDto {
  statusCode: number;
  message: string;
  data: PaginatedData;
}
